__author__ = 'Joe'

CONTEXTS = dict(
    CPRS='OR CPRS GUI CHART',
    CAPRI='DVBA CAPRI GUI',
    MDWS='MWVS MEDICAL DOMAIN WEB SVCS'
)

GET_VAR_VAL = 'XWB GET VARIABLE VALUE'

FILES = dict(
    USERS=('200', 'NEW PERSON'),
    PATIENTS=('2', 'PATIENT'),
    CONTEXTS=('19', 'OPTION'),
    CONTROL_POINTS=('410', 'CONTROL POINT ACTIVITY'),
    FMS_TXNS=('417', 'FMS TRANSACTIONS')
)