# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'payrec_widget.ui'
#
# Created: Sun Nov 29 09:46:11 2015
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PayrecWidget(object):
    def setupUi(self, PayrecWidget):
        PayrecWidget.setObjectName("PayrecWidget")
        PayrecWidget.resize(500, 500)
        self.verticalLayoutWidget = QtWidgets.QWidget(PayrecWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 481, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rec_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rec_label.setText("")
        self.rec_label.setObjectName("rec_label")
        self.verticalLayout.addWidget(self.rec_label)
        self.gsf_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.gsf_label.setText("")
        self.gsf_label.setObjectName("gsf_label")
        self.verticalLayout.addWidget(self.gsf_label)
        self.rec_table = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.rec_table.setRowCount(22)
        self.rec_table.setColumnCount(1)
        self.rec_table.setObjectName("rec_table")
        item = QtWidgets.QTableWidgetItem()
        self.rec_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rec_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rec_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.rec_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.rec_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.rec_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.rec_table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.rec_table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.rec_table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.rec_table.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.rec_table.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.rec_table.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.rec_table.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.rec_table.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.rec_table.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.rec_table.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.rec_table.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.rec_table.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.rec_table.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.rec_table.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.rec_table.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.rec_table.setVerticalHeaderItem(21, item)
        self.rec_table.horizontalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.rec_table)

        self.retranslateUi(PayrecWidget)
        QtCore.QMetaObject.connectSlotsByName(PayrecWidget)

    def retranslateUi(self, PayrecWidget):
        _translate = QtCore.QCoreApplication.translate
        PayrecWidget.setWindowTitle(_translate("PayrecWidget", "Employee Pay Record"))
        item = self.rec_table.verticalHeaderItem(0)
        item.setText(_translate("PayrecWidget", "8B NORMAL HOURS"))
        item = self.rec_table.verticalHeaderItem(1)
        item.setText(_translate("PayrecWidget", "NORMAL HOURS"))
        item = self.rec_table.verticalHeaderItem(2)
        item.setText(_translate("PayrecWidget", "OASDI TAX VA SHARE CPPD"))
        item = self.rec_table.verticalHeaderItem(3)
        item.setText(_translate("PayrecWidget", "FEGLI VA SHARE CPPD"))
        item = self.rec_table.verticalHeaderItem(4)
        item.setText(_translate("PayrecWidget", "HEALTH BENEFITS VA SHARE CPPD"))
        item = self.rec_table.verticalHeaderItem(5)
        item.setText(_translate("PayrecWidget", "RETIREMENT VA SHARE CPPD"))
        item = self.rec_table.verticalHeaderItem(6)
        item.setText(_translate("PayrecWidget", "TSP CSF GOV BASIC CONTRIB"))
        item = self.rec_table.verticalHeaderItem(7)
        item.setText(_translate("PayrecWidget", "TSP GSF GOV BASIC CONTRIB"))
        item = self.rec_table.verticalHeaderItem(8)
        item.setText(_translate("PayrecWidget", "TSP CSF GOV MATCH CONTRIB"))
        item = self.rec_table.verticalHeaderItem(9)
        item.setText(_translate("PayrecWidget", "TSP GSF GOV MATCH CONTRIB"))
        item = self.rec_table.verticalHeaderItem(10)
        item.setText(_translate("PayrecWidget", "BASE PAY CPPD"))
        item = self.rec_table.verticalHeaderItem(11)
        item.setText(_translate("PayrecWidget", "HOLIDAY AMT"))
        item = self.rec_table.verticalHeaderItem(12)
        item.setText(_translate("PayrecWidget", "OVERTIME AMT CPPD"))
        item = self.rec_table.verticalHeaderItem(13)
        item.setText(_translate("PayrecWidget", "GROSS PAY PLUS BENEFITS CPPD"))
        item = self.rec_table.verticalHeaderItem(14)
        item.setText(_translate("PayrecWidget", "OVERTIME HOURS WK 1"))
        item = self.rec_table.verticalHeaderItem(15)
        item.setText(_translate("PayrecWidget", "OVERTIME HOURS WK 2"))
        item = self.rec_table.verticalHeaderItem(16)
        item.setText(_translate("PayrecWidget", "OVERTIME AMT WK 1"))
        item = self.rec_table.verticalHeaderItem(17)
        item.setText(_translate("PayrecWidget", "OVERTIME AMT WK 2"))
        item = self.rec_table.verticalHeaderItem(18)
        item.setText(_translate("PayrecWidget", "HRS EXCESS 8 DAY WK 1"))
        item = self.rec_table.verticalHeaderItem(19)
        item.setText(_translate("PayrecWidget", "HRS EXCESS 8 DAY WK 2"))
        item = self.rec_table.verticalHeaderItem(20)
        item.setText(_translate("PayrecWidget", "HRS EXCESS 8 DAY AMT WK 1"))
        item = self.rec_table.verticalHeaderItem(21)
        item.setText(_translate("PayrecWidget", "HRS EXCESS 8 DAY AMT WK 2"))

